### ISSUE TITLE
[unic-pr-review] review-pr docs suggest a `--base` flag that does not exist

### ISSUE THREAD

**Issue by orioltf** [unic/unic-agents-plugins#161]
## Problem

`apps/claude-code/unic-pr-review/commands/review-pr.md:55` tells the user, when a diff is very large, to "suggest tightening the base branch (e.g. `--base feature/x`)". **No `--base` flag exists anywhere in this plugin**, so a user who follows the suggestion passes an argument the tool silently ignores.

```text
- **Diff exceeds ~2000 lines or ~200 KB**: warn the user that the review may be
  incomplete and suggest tightening the base branch (e.g. `--base feature/x`).
```

## Root cause

The base branch is resolved automatically by `scripts/lib/base-branch-resolver.mjs`, which takes **no CLI argument** — it derives the branch via `git symbolic-ref refs/remotes/origin/HEAD` and then a `develop → main → master` fallback chain (`resolveBaseBranch(exec)`, ~line 41). The `review-pr` command's `argument-hint` is `[<PR URL>]` and Step 1 only branches on "URL given" vs "no argument"; there is no override path. So the documented `--base feature/x` escape hatch is fiction.

## Why this was deferred from PR #158

Spotted by the comment-analyzer during the full review of PR #158 (remaining five aspect agents + conditional spawning, closes #146). The line is **pre-existing context** (not introduced by #158) and concerns the base-branch resolver, which is orthogonal to that PR's scope (aspect agents + conditional spawning). Deferred to keep #158 focused; flagged here so it can be picked up right after #158 merges.

## Proposed resolution (pick one during triage)

1. **Doc-only fix (smallest):** remove the bogus `--base feature/x` example, or replace it with accurate guidance — e.g. "review a smaller branch, or push an intermediate branch and review against that," since the resolver auto-detects the base and has no override today.
2. **Implement a real override + update the doc:** add a base-branch override to `unic-pr-review` (an env var or a command flag) and make the doc reference the real mechanism. This would warrant its own spec. ADR-0009 (Pre-PR Mode) is the relevant decision record.

Option 1 unblocks accuracy immediately; option 2 is a feature.

## Acceptance criteria

- `commands/review-pr.md` no longer references any flag/mechanism that the plugin does not implement.
- If an override is implemented (option 2): the documented invocation actually changes the resolved base branch, with a test in `tests/` and a CHANGELOG entry.
- `pnpm --filter unic-pr-review verify:changelog` passes; `pnpm ci:check` clean.

## References

- File: `apps/claude-code/unic-pr-review/commands/review-pr.md:55`
- Resolver: `apps/claude-code/unic-pr-review/scripts/lib/base-branch-resolver.mjs` (`resolveBaseBranch`, ~line 41)
- Found in: PR #158 (full multi-agent review, comment-analyzer)
- Related: ADR-0009 (Pre-PR Mode)
